---
version: '2'
services:
  kafka-ssl-4:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-ssl-4
    ports:
      - "19192:19192"
      - "19194:19194"
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
      KAFKA_LISTENERS: PLAINTEXT://:19192,SSL://:19194
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:19192,SSL://116.196.123.103:19194
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker4.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker4_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker4_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker4.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker4_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_LOG_RETENTION_HOURS: 48
    volumes:
      - ${KAFKA_SSL_SECRETS_DIR}:/etc/kafka/secrets
    network_mode: host

  kafka-ssl-5:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-ssl-5
    ports:
      - "29192:29192"
      - "29194:29194"
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
      KAFKA_LISTENERS: PLAINTEXT://:29192,SSL://:29194
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:29192,SSL://116.196.123.103:29194
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker5.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker5_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker5_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker5.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker5_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_LOG_RETENTION_HOURS: 48
    volumes:
      - ${KAFKA_SSL_SECRETS_DIR}:/etc/kafka/secrets
    network_mode: host

  kafka-ssl-6:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-ssl-6
    ports:
      - "39192:39192"
      - "39194:39194"
    environment:
      KAFKA_BROKER_ID: 6
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
      KAFKA_LISTENERS: PLAINTEXT://:39192,SSL://:39194
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:39192,SSL://116.196.123.103:39194
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker6.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker6_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker6_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker6.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker6_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_LOG_RETENTION_HOURS: 48
    volumes:
      - ${KAFKA_SSL_SECRETS_DIR}:/etc/kafka/secrets
    network_mode: host
